version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t kaveripansare/stockapp:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push kaveripansare/stockapp:latest